### ISSUE TITLE
Napisanie  specyfikacji funkcjonalna projektu.

### ISSUE THREAD

**Issue by Annti** [Annti/Projekt-Grupowy#1]
Ja proponuje plik WORD format 93/2000.

**Comment by Annti** [comment]
Co musi się znaleźć w specyfikacji na pewno w jakiej technologi będziemy pracować i jakiego sprzętu chcemy używać.
Ja proponuje głownie free software i open source - wybór Python do połączenia z kamerą i alarmem (sprzet z którym możemy się połączyć po kablu ethernetowym najlepiej protokołem TCP/IP), baza danych - moja propozycja mysql bo jest prosto i wszyscy znają ale możemy się zastanowić nad pójściem w postgresql - tu mam mieszane uczucia, ale warto zainwestować w naukę czas na przyszłość - do obsługi Android albo jakaś aplikacja w Java? 
Głowne zadania systemu co będzie robił i jjak zakładamy, że będzie to robił.
Co wy na to?

**Comment by Wlosiak** [comment]
Tak sądze, że jak chcecie sie uczyć itd. to można postgresql wiadomo mysql lepiej znamy :)
Jeśli chodzi o aplikacje to w javie nam będzie napewno łatwiej napisać niż w innym języku :)

Androida to można jako dodatkowo zrobić tak sądze do tego.

**Comment by Annti** [comment]
Trzeba się zdecydować na technologie bo będzie trzeba zaraz przydzielić zadania w kolejnym etpaie - ja się dostosuje - głosowanie co do bazy ważne.

**Comment by Wlosiak** [comment]
Dobra to ja jestem za JAVA i mysql

**Comment by Annti** [comment]
W sumie PYTHON JAVA MYSQL. W takim razie ;) Trzeba dziś i jutro napisać tą specyfikacje wrzucę pierwszego worda za jakieś 3 h.
